services:
    tailscale:
        image: tailscale/tailscale:latest
        container_name: tailscale-node
        restart: unless-stopped
        cap_add:
            - NET_ADMIN
        devices:
            - /dev/net/tun:/dev/net/tun
        environment:
            - TZ=${TZ:-Asia/Tokyo}
            - TS_AUTHKEY=${TS_AUTHKEY}
            - TS_HOSTNAME=${TS_HOSTNAME:-adguard-home}
            - TS_STATE_DIR=/var/lib/tailscale
            - TS_USERSPACE=false
            - TS_EXTRA_ARGS=--accept-dns=false
        volumes:
            - ./data_tailscale:/var/lib/tailscale
        networks:
            adgnet:
                ipv4_address: ${MACVLAN_IP}

    adgrd:
        image: adguard/adguardhome:latest
        container_name: adguard-home
        restart: unless-stopped
        network_mode: "service:tailscale"
        volumes:
            - ./config:/opt/adguardhome/conf
            - ./work:/opt/adguardhome/work

networks:
    adgnet:
        name: ${MACVLAN_NETWORK_NAME:-macvlan_lan}
        external: true
